[GLOBAL]
pants_version = "2.21.0"

build_file_prelude_globs = ["pants-plugins/macros.py"]
build_patterns = ["BUILD.pants", "BUILD"]
pantsd = true 

backend_packages = [
    "pants.backend.docker",
    "pants.backend.docker.lint.hadolint",
    "pants.backend.python",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
]

[docker]
use_buildx = true

[python]
interpreter_constraints = [">=3.9,<4"]

[anonymous-telemetry]
enabled = false
